- name: Install nginx
  hosts: frontend
  tasks:
   - name: install inginx sever
     ansible.builtin.package:
      name: nginx
      state: present

- name: start nginx 
  ansible.builtin.service:
   name: nginx
   state: started
   enabled: yes