- name: command vs shell
  hosts: frontend
  tasks:
  - name: redirect to output file
    #ansible.builtin.command: "ls -lrt  > /tmp/output.txt"
    ansible.builtin.shell: "ls -lrt  > /tmp/output.txt" 
    register: resulut
  - name: print ourput
    ansible.builtin.debug:
     msg: "{{ result }}"
    